// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRXEKwhIZikCH4O-uBnJjKoAAO4xXdtLE',
    appId: '1:733261168366:web:cd998cc420f90db84cfdff',
    messagingSenderId: '733261168366',
    projectId: 'siparis-takip-42fa9',
    authDomain: 'siparis-takip-42fa9.firebaseapp.com',
    storageBucket: 'siparis-takip-42fa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWHUZiP7Y97XNqY6mVve8wkuCcu5UcYQ',
    appId: '1:733261168366:android:7652bbece36c067b4cfdff',
    messagingSenderId: '733261168366',
    projectId: 'siparis-takip-42fa9',
    storageBucket: 'siparis-takip-42fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyjYRqH4l4f4klpyMizcYKire7UYWZGvw',
    appId: '1:733261168366:ios:09aa2cd71c630bdc4cfdff',
    messagingSenderId: '733261168366',
    projectId: 'siparis-takip-42fa9',
    storageBucket: 'siparis-takip-42fa9.firebasestorage.app',
    iosBundleId: 'com.example.mbtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyjYRqH4l4f4klpyMizcYKire7UYWZGvw',
    appId: '1:733261168366:ios:09aa2cd71c630bdc4cfdff',
    messagingSenderId: '733261168366',
    projectId: 'siparis-takip-42fa9',
    storageBucket: 'siparis-takip-42fa9.firebasestorage.app',
    iosBundleId: 'com.example.mbtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRXEKwhIZikCH4O-uBnJjKoAAO4xXdtLE',
    appId: '1:733261168366:web:b75bcb06256f707e4cfdff',
    messagingSenderId: '733261168366',
    projectId: 'siparis-takip-42fa9',
    authDomain: 'siparis-takip-42fa9.firebaseapp.com',
    storageBucket: 'siparis-takip-42fa9.firebasestorage.app',
  );
}
